name: kayo_package
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0               # Feb 3, 2021
  fluro: ">=1.6.1  <=10.0.0"      #  Mar 1, 2021  2.0.3
  connectivity: ">=0.4.8+2 <=10.0.0"   # May 26, 2021  3.0.6
#  url_launcher: ">=5.4.10 <=10.0.0"   # Jul 4, 2021  6.0.9
  flutter_spinkit: ">=4.1.2+1 <=10.0.0"    #  Mar 4, 2021     5.0.0
  pub_semver: ">=1.4.4 <=10.0.0"          #Feb 5, 2021   2.0.0
  flutter_slidable: ">=0.5.5 <=10.0.0"      # Jul 18, 2021 0.6.0
  dio: ">=2.1.0 <=10.0.0"                   #Mar 28, 2021   4.0.0
  event_bus: ">=1.1.1 <=10.0.0"          # Mar 4, 2021  2.0.0
#  path_drawing: ">=0.5.1   <=10.0.0"       #  May 5, 2021 0.5.1
  #  cached_network_image: ">=2.0.0   <=10.0.0"       #  May 5, 2021 3.1.0
#  flutter_easyloading: ">=2.0.0   <=10.0.0"       #  Mar 12, 2021  ^3.0.0
#  back_button_interceptor: ^6.0.0

  convert: ">=2.1.0 <=10.0.0"             # Jun 24, 2021  3.0.1
  crypto: ">=1.0.0 <=10.0.0"              #Apr 1, 2021  3.0.1
  json_annotation: ">=3.0.1 <=10.0.0"     # Jul 13, 2021   4.1.0
  provider: ">=4.0.0 <=10.0.0"            # Jul 12, 2021  5.0.0 / 6.0.0-dev
#  fluttertoast: ">=3.1.2 <=20.0.0"        # May 19, 2021   8.0.7
  #  extended_image: ^6.2.0
#  convex_bottom_bar: ^3.0.0
  lpinyin: ^2.0.2  #latest version
  http: ^0.13.1

  #  pull_to_refresh: ">=1.5.8 <=10.0.0"       # May 7, 2021 2.0.0
#  pull_to_refresh:
#    git:
#      url: https://gitee.com/kayoxu/pull_to_refresh-2.0.0.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ">=1.8.0 <=20.0.0"  # Jul 9, 2021  2.0.6
  json_serializable: ">=3.0.1 <=20.0.0"     # Jul 13, 2021   5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
