name: kayo_package
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1               # Jan 6, 2020
#  flutter_svg: ^0.17.3+1        # Mar 9, 2020
  fluro: ^1.6.1               # Mar 28, 2020
#  cupertino_icons: ^0.1.2     # Apr 5, 2018
  flutter_redux: ^0.6.0       # Dec 4, 2019
  connectivity: ^0.4.8+2      # Mar 9, 2020
  url_launcher: ^5.4.10        # May 21, 2020
  flutter_markdown: ^0.3.4    # Feb 25, 2020
  flutter_spinkit: ^4.1.2+1  # Mar 26, 2020
  pub_semver: ^1.4.4          # Mar 16, 2020
#  flutter_statusbar: ^0.0.1   # Jul 11, 2018
  flutter_slidable: ^0.5.4    # Oct 6, 2019
#  dio: ^2.1.13                # Jul 10, 2019
  dio: ^3.0.9                # Feb 24, 2020
  event_bus: ^1.1.1          # Jan 21, 2020
  path_drawing: ^0.4.1        # May 7, 2019
#  cached_network_image: ^1.1.2+1    #  Oct 17, 2019
  cached_network_image: ^2.0.0    #   Dec 31, 2019

  convert: ^2.1.1             # Dec 19, 2018
  crypto: ^2.1.3              # Dec 6, 2019
  json_annotation: ^3.0.1     # Dec 23, 2019
  cool_ui: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0        #  Mar 5, 2020
  json_serializable: ^3.0.1   # Dec 23, 2019

flutter:

#  assets:
#    - assets/
